name: Test that Jupyter Book builds

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    if: github.repository == 'UBICenter/ubicenter.dev'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install jupyter-book


    # Build the book
    - name: Build the book
      run: |
        jupyter-book build jb
