name: Test that Jupyter Book builds
on: [push, pull_request]
jobs:
  build-and-deploy:
    if: github.repository == 'UBICenter/ubicenter.dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: reponame
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Build
        shell: bash -l {0}
        run: |
          cd jb
          jb build .
